log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

  rtc:
    # https
    address: ":9001"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "viktor@adslab.io"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      #httpChallenge:
      #  entryPoint: web
      dnsChallenge:
         provider: cloudflare

http:
  routers:

    flower-router:
      rule: "Host(`flower.x.hol.is`)"
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: flower

    flower-secure-router:
      rule: "Host(`flower.x.hol.is`)"
      entryPoints:
        - web-secure
      service: flower
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    rtc:
      rule: "Host(`hol.is`)"
      entryPoints:
        - rtc
      service: rtc
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    web-router:
      rule: "Host(`hol.is`) || Host(`www.hol.is`) || HostRegexp(`{subdomain:[a-z0-9-]+}.hol.is`)" 
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    web-secure-router:
      rule: "Host(`hol.is`) || Host(`www.hol.is`)  || HostRegexp(`{subdomain:[a-z0-9-]+}.hol.is`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
        - test-compress
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
        domains:
          - main: "hol.is"
            sans:
              - "*.hol.is"

  middlewares:
    test-compress:
      compress: {}

    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    rtc:
      loadBalancer:
        servers:
          - url: http://rtc:9001

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
