stages:
  - black
  - test

variables:
  POSTGRES_USER: 'lesgens'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_lesgens'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

black:
  stage: Static Analysis
  image: milansuk/python-black:latest
  script:
    - black --fast

pytest:
  stage: test
  image: python:3.7
  tags:
    - docker
  services:
    - docker
  before_script:
    - docker-compose -f local.yml build
    # Ensure celerybeat does not crash due to non-existent tables
    - docker-compose -f local.yml run --rm django python manage.py migrate
    - docker-compose -f local.yml up -d
  script:
    - docker-compose -f local.yml run django pytest

