log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

  rtc:
    # https
    address: ":9001"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "viktor@adslab.io"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      #httpChallenge:
      #  entryPoint: web
      dnsChallenge:
         provider: cloudflare

http:
  routers:
    web-router:
      rule: "Host(`holis.chat`) || Host(`www.holis.chat`) || HostRegexp(`{subdomain:[a-z]+}.holis.chat`)" 
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    web-secure-router:
      rule: "Host(`holis.chat`) || Host(`www.holis.chat`)  || HostRegexp(`{subdomain:[a-z]+}.holis.chat`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
        - test-compress
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
        domains:
          - main: "holis.chat"
            sans:
              - "*.holis.chat"

    openfire-router:
      rule: "Host(`chat.holis.chat`)" 
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    openfire-secure-router:
      rule: "Host(`chat.holis.chat`)"
      entryPoints:
        - web-secure
      service: openfire
      middlewares:
        - csrf
        - test-compress
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    bosh-secure-router:
      rule: "Host(`bosh.chat.holis.chat`)"
      entryPoints:
        - web-secure
      service: bosh
      middlewares:
        - csrf
        - test-compress
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`flower.holis.chat`)"
      entryPoints:
        - web-secure
      service: flower
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
    
    rtc:
      rule: "Host(`holis.chat`)"
      entryPoints:
        - rtc
      service: rtc
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  middlewares:
    test-compress:
      compress: {}

    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    openfire:
      loadBalancer:
        servers:
          - url: http://openfire:9090

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    rtc:
      loadBalancer:
        servers:
          - url: http://rtc:9001

    bosh:
      loadBalancer:
        servers:
          - url: http://openfire:7070


providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
